wd<-getwd()
filename<-"household_power_consumption.txt"
# hpc<-read.delim(filename,header=TRUE,sep=";",dec=".")
hpc1<-subset(hpc,hpc$Date=="1/2/2007"|hpc$Date=="2/2/2007")
hpc1$Time<-strptime(hpc1$Time,format="%H:%M:%S")
hpc1[1:1440,"Time"]<-format(hpc1[1:1440,"Time"],"2007-02-01 %H:%M:%S")
hpc1[1441:2880,"Time"]<-format(hpc1[1:1440,"Time"],"2007-02-02 %H:%M:%S")
#hpc1$Global_active_power<-as.numeric(as.character(hpc1$Global_active_power))
#hpc1$Global_reactive_power<-as.numeric(as.character(hpc1$Global_reactive_power))
hpc1$Sub_metering_1<-as.numeric(as.character(hpc1$Sub_metering_1))
hpc1$Sub_metering_2<-as.numeric(as.character(hpc1$Sub_metering_2))
hpc1$Sub_metering_3<-as.numeric(as.character(hpc1$Sub_metering_3))
png(file="plot3.png",width=480, height=480)
plot(hpc1$Time,hpc1$Sub_metering_1,type="l",ylab="Energy sub metering")
points(hpc1$Time,hpc1$Sub_metering_2,type="l",col="red")
points(hpc1$Time,hpc1$Sub_metering_3,type="l",col="blue")
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
title(main="Energy sub-metering")
dev.off()
